"""
src/export.py — Dynamic Export orchestrator to JSON and Markdown.
"""

import datetime
import json
import os
import importlib
import inspect
from dataclasses import asdict

from src.models import ScanResult


def md_table(headers: list[str], rows: list[list]) -> str:
    """Helper to generate Markdown tables. Can be imported by modules."""
    h = " | ".join(headers)
    sep = " | ".join(["---"] * len(headers))
    lines = [f"| {h} |", f"| {sep} |"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines) + "\n"


def export_results(
    result: ScanResult, target: str, modules_selected: list[str]
) -> tuple[str, str]:
    os.makedirs("reports", exist_ok=True)

    safe_name = (
        target.replace("https://", "")
        .replace("http://", "")
        .replace("/", "_")
        .replace(":", "_")
    )
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    base = os.path.join("reports", f"{safe_name}_{ts}")

    # ── JSON (Immutable Data Dump) ───────────────────────────────────
    json_path = f"{base}.json"
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(asdict(result), fh, indent=2, default=str)

    # ── Markdown (Dynamic Autoload) ──────────────────────────────────
    md_path = f"{base}.md"
    with open(md_path, "w", encoding="utf-8") as fh:
        W = fh.write

        # ── Global Header ────────────────────────────────────────────
        W("# 🛡️ K-Vanguard Security Assessment Report\n\n")
        W("| Field | Value |\n|---|---|\n")
        W(f"| **Target** | {result.target} |\n")
        W(f"| **Timestamp** | {result.timestamp} |\n")
        W(f"| **Security Score** | {result.score}/100 |\n\n")
        W("---\n\n")

        # ── Dynamic Module Exports ───────────────────────────────────
        for mod_id in modules_selected:
            try:
                mod_obj = importlib.import_module(f"src.modules.{mod_id}")

                # Cari fungsi yang namanya berawalan "export_"
                export_func = None
                for name, obj in inspect.getmembers(mod_obj, inspect.isfunction):
                    if name.startswith("export_"):
                        export_func = obj
                        break

                # Eksekusi kalau ketemu, passing ScanResult dan fungsi Write
                if export_func:
                    export_func(result, W)

            except Exception as e:
                W(
                    f"\n> [!WARNING]\n> Failed to generate report section for `{mod_id}`: {e}\n\n"
                )

        # ── Footer ───────────────────────────────────────────────────
        W("---\n\n")
        W(f"*Generated by K-Vanguard v1.0.0-rc.1 — {result.timestamp}*\n")

    return json_path, md_path
